# Configuraci칩n de Railway para proyectos con frontend y backend

[build]
  # Comando para instalar dependencias y construir el frontend
  frontend = "cd frontend && npm install && npm run build"

[services.backend]
  # Configuraci칩n para el backend
  start = "cd backend && npm install && node server.js"

[static]
  # Configuraci칩n para servir los archivos est치ticos del frontend
  path = "frontend/build"